### ISSUE TITLE
Installation check failed for hurl 6.1.0

### ISSUE THREAD

**Issue by Nhattd97** [gacts/install-hurl#93]
After Hurl released the version 6.1.0 today. The Installation check failed with error "Error: The process '/tmp/hurl-6.1.0/hurl' failed with exit code 1". It worked for Hurl 6.0.0 yesterday.

![Image](https://github.com/user-attachments/assets/3fe40419-23c7-488f-b07e-55aeaa8272da)

**Comment by tarampampam** [comment]
Could you provide a full example of the action you have used?

Af far as I can see, it works well even with the latest version of `hurl`:

![Image](https://github.com/user-attachments/assets/2cade9a4-e050-4faf-a3b1-928358a4b8ae)

With cache miss:
![Image](https://github.com/user-attachments/assets/c5f2cc2b-cf36-4b1e-bbe6-5fc883573e71)

And hit:
![Image](https://github.com/user-attachments/assets/d6349c09-d5f6-4090-98fe-171ede176d10)

**Comment by Nhattd97** [comment]
Hi, this is what I used.
```
    - name: "Set up Hurl"
      if: ${{ hashFiles('hurl/') != '' }}
      uses: gacts/install-hurl@v1
```

![Image](https://github.com/user-attachments/assets/0c86f0ff-5dba-4e39-af4a-3d9a4d23b105)

![Image](https://github.com/user-attachments/assets/7944a33e-9dd3-484d-8873-1859e779b75c)

**Comment by tarampampam** [comment]
Is the runner self-hosted or shared? What is architecture? Have you tried clearing the action cache, just in case?

**Comment by tarampampam** [comment]
I have released a new version with all the latest dependency updates. It likely won't help, but please try restarting the action once more

**Comment by Nhattd97** [comment]
yes, it's running on the self-hosted runner, These runners were setup by the Org so I not sure about the architecture. But from the runner tags, it's X64, Linux. I tried to clear all the caches. 

Sure, let me try again

**Comment by Nhattd97** [comment]
Still encounter the error. It seems like just occur on our self-hosted runners, It's worked for the Github ubuntu runner

```
name: "Hurl install"
on: [push]

jobs:
  ashburn:
    name: ashburn runners
    runs-on: ashburn
    steps:
      - name: "Set up Hurl"
        uses: gacts/install-hurl@v1
  alpha:
    name: alpha runners
    runs-on: alpha
    steps:
      - name: "Set up Hurl"
        uses: gacts/install-hurl@v1
  ubuntu:
    name: ubuntu runners
    runs-on: ubuntu-latest
    steps:
      - name: "Set up Hurl"
        uses: gacts/install-hurl@v1
```

![Image](https://github.com/user-attachments/assets/0cdc0a74-d636-4263-b2eb-efc9a4d3c2e0)

**Comment by tarampampam** [comment]
As a temporary workaround, I have added an option to disable caching the distributive in #95.  

```diff
      - name: "Set up Hurl"
        uses: gacts/install-hurl@v1
+       with: {disable-cache: true}
```  

Feel free to use it until the issue with the runners hosted by your company is resolved. Sound good?

**Comment by Nhattd97** [comment]
The flag will not help resolve the issue, so I used the previous version of Hurl as a temporary fix for now.
```
- name: "Set up Hurl"
      uses: gacts/install-hurl@v1
      with:
        version: 6.0.0
```

**Comment by Nhattd97** [comment]
Thanks for your quick response on this.

**Comment by tarampampam** [comment]
It sounds quite strange... Also, you can try to pin the action version to:  

```diff
-       uses: gacts/install-hurl@v1
+       uses: gacts/install-hurl@v1.3.0
```  

> In programming, we have only two types of problems: variable naming and cache invalidation.

**Comment by tarampampam** [comment]
> Thanks for your quick response on this

It's just part of my morning routine - you're welcome!

**Comment by tarampampam** [comment]
Can the issue be closed?

**Comment by Nhattd97** [comment]
> It sounds quite strange... Also, you can try to pin the action version to:

here you are
![Image](https://github.com/user-attachments/assets/93df3756-2306-4b42-a8ea-cbd2725c80bd)

> Can the issue be closed?

Sure, thanks again
